services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '4000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    networks:
      - telemetry
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: unless-stopped
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"   # Tempo API
      - "4417:4317"   # OTLP gRPC
      - "4418:4318"   # OTLP HTTP
    networks:
      - telemetry
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: unless-stopped
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--web.enable-remote-write-receiver"
  #   volumes:
  #     - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  #     - prometheus-data:/prometheus
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - telemetry

volumes:
  grafana-storage: {}
  tempo-data: {}
  prometheus-data: {}

networks:
  telemetry:
    external: true
